name: mvn test
inputs:
  args:
    description: "arguments to run for mvn"
    required: true
runs:
  using: "composite"
  steps:
    - name: mvn test
      uses: docker://maven:3.8.5-amazoncorretto-11
      with:
        entrypoint:  mvn
        args: ${{ inputs.args }}